[CI]updated drone.star file
owncloud/contacts pull request #732
Opened 2022-03-16 05:03 UTC by sushmita56

## Description
This is an update on drones.star file 
- using drone-cancel-previous-builds
- using thegeeklab/drone-github-comment instead of jmccann/drone-github-comment for github comments 
- moving docker image references to constants
- using caches images
- Do not run PHP unit tests with Oracle by default

## Related Issue
- Part of issue: 
- https://github.com/owncloud/QA/issues/700
- https://github.com/owncloud/QA/issues/717
- https://github.com/owncloud/QA/issues/729
- https://github.com/owncloud/QA/issues/728
- https://github.com/owncloud/core/issues/38679

2022-03-16 06:08 UTC, phil-davis commented
There are still a lot of diffs from what is in the activity app master branch. Please copy all the code from there - we want it to be exactly the same in each oC10 app.

2022-03-16 06:28 UTC, kiranparajuli589 requested changes
also add `.idea` dir to the `gitignore`

2022-03-16 06:28 UTC, kiranparajuli589 commented on .drone.star
>                  "message_file": "%s/comments.file" % dir["base"],
this new image has a little different configuration. please refer to the changes in the activity app and fix the case here

2022-03-16 11:34 UTC, amrita-shrestha submitted a review, later dismissed

2022-03-16 11:34 UTC, amrita-shrestha commented on .drone.star
> +MAILHOG = "mailhog/mailhog"
```suggestion
MAILHOG_MAILHOG = "mailhog/mailhog"
```

2022-03-16 11:34 UTC, amrita-shrestha commented on .drone.star
> +DRONE_CI_ALPINE = "drone/cli:alpine"
```suggestion
DRONE_CLI = "drone/cli:alpine"
```

2022-03-16 11:34 UTC, amrita-shrestha commented on .drone.star
> +OC_SCALITY_S3_SERVER = "owncloudci/scality-s3server"
```suggestion
OC_CLI_SCALITY_S3_SERVER = "owncloudci/scality-s3server"
```

2022-03-17 04:16 UTC, kiranparajuli589 requested changes, later dismissed

2022-03-17 04:16 UTC, kiranparajuli589 commented on .drone.star
> +MINIO_MC_RELEASE_2020_VERSION = "minio/mc:RELEASE.2020-12-18T10-53-53Z"
```suggestion
MINIO_MC = "minio/mc:RELEASE.2020-12-18T10-53-53Z"
```

2022-03-17 04:16 UTC, kiranparajuli589 commented on .drone.star
> +        "steps": skipIfUnchanged(ctx, "lint") +
```suggestion
        "steps": skipIfUnchanged(ctx, "unit-tests") +
```

2022-03-17 04:16 UTC, kiranparajuli589 commented on .drone.star
> +                    "steps": skipIfUnchanged(ctx, "lint") +
```suggestion
                    "steps": skipIfUnchanged(ctx, "unit-tests") +
```

2022-03-17 04:16 UTC, kiranparajuli589 commented on .drone.star
> +                    "steps": skipIfUnchanged(ctx, "lint") +
```suggestion
                    "steps": skipIfUnchanged(ctx, "acceptance-tests") +
```

2022-03-17 04:16 UTC, kiranparajuli589 commented on .drone.star
> +                 skipIfUnchanged(ctx, "lint") +
```suggestion
                 skipIfUnchanged(ctx, "unit-tests") +
```

2022-03-17 22:23 UTC, phil-davis approved these changes

2022-03-17 22:25 UTC, merged